[package]
name = "recommend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["rt-multi-thread","macros"] }
tonic = "0.13.0"
prost = "0.13.5"

[build-dependencies]
tonic-build = "0.13.0"
